project_id = "yjdyuywsqlzejlfvgdmy"

[local]
database_host = "localhost"
database_port = 54322
database_name = "postgres"
database_user = "postgres"
database_password = "postgres"

[migrations]
dir = "supabase/migrations"

[functions]
dir = "supabase/functions"
