// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjdyuywsqlzejlfvgdmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZHl1eXdzcWx6ZWpsZnZnZG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1Njk1MTgsImV4cCI6MjA2ODE0NTUxOH0.K5TLvtCIGP8QBr8QA1slUHCkpmeRZAHMAUD898i-iBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});